# Generated by Django 4.2 on 2023-04-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('force', models.FloatField()),
                ('weight', models.FloatField()),
                ('mapcode', models.CharField(max_length=10)),
            ],
        ),
    ]
