# Generated by Django 4.2 on 2023-04-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='mapcode',
            field=models.CharField(max_length=20),
        ),
    ]
